Vagrant.configure("2") do |config|
  config.vm.box = "precise32"
  config.vm.box_url = "http://files.vagrantup.com/precise32.box"

  config.vm.network "private_network", ip: "192.168.56.101"
  config.vm.network "forwarded_port", guest: 3000, host: 3000

  config.vm.synced_folder "../", "/var/www/algebra"

  # Uncomment the following line to allow for symlinks
  # in the app folder. This will not work on Windows, and will
  # not work with Vagrant providers other than VirtualBox
  # config.vm.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/app", "1"]

  config.vm.provision :chef_solo do |chef|
    chef.add_recipe "nodejs"
    # chef.add_recipe "mongodb-debs"
    chef.json = {
      "nodejs" => {
        "version" => "0.10.24"
        # uncomment the following line to force
	# recent versions (> 0.8.5) to be built from
	# the source code
	# , "from_source" => true
      }
    }
  end

  config.vm.provision :shell, :inline => "sudo apt-get install -y build-essential --no-install-recommends"
  config.vm.provision :shell, :inline => "sudo apt-get -y install git-core"
  config.vm.provision :shell, :inline => "mkdir -p /var/www/algebra/node_modules"
  config.vm.provision :shell, :inline => "(cd /var/www/algebra && npm install)"
  config.vm.provision :shell, :inline => "sudo npm install -g grunt-cli"
  config.vm.provision :shell, :inline => "sudo npm install browserify -g"
end
